require "SDK/MengluuSDK"
require "SDK/RoleModelSDK"
require "SDK/XluaSDK"
require "SDK/ResourcesSDK"
require "SDK/ResManagerSDK"
require "SDK/ModuleSDK"
require "SDK/InterludeSDK"
require "SDK/LocallizationSDK"